// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful';
import { Document } from '@contentful/rich-text-types';

export interface IBlogPostFields {
  /** Post TItle */
  postTItle?: string | undefined;

  /** Slug Text */
  slugText?: string | undefined;

  /** Publish Date */
  publishDate?: string | undefined;

  /** Sub Title */
  subTitle?: string | undefined;

  /** SEO Title */
  seoTitle?: string | undefined;

  /** SEO Meta Description */
  seoMetaDescription?: string | undefined;

  /** Featured Image */
  featuredImage?: Asset | undefined;

  /** Author */
  author?: Entry<{ [fieldId: string]: unknown }> | undefined;

  /** Post Content */
  postContent?: Document | undefined;
}

export interface IBlogPost extends Entry<IBlogPostFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'blogPost';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ICoachFields {
  /** Appearance Order */
  appearanceOrder?: number | undefined;

  /** SEO Title */
  seoTitle?: string | undefined;

  /** SEO Meta Description */
  seoMetaDescription?: string | undefined;

  /** Name */
  name?: string | undefined;

  /** Profile Image */
  profileImage?: Asset | undefined;

  /** Welcome Message */
  welcomeMessage?: Document | undefined;

  /** Biography */
  biography?: Document | undefined;

  /** Book Time Photo */
  bookTimePhoto?: Asset | undefined;

  /** LinkedIn Profile URL */
  linkedInProfileUrl?: string | undefined;
}

export interface ICoach extends Entry<ICoachFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'coach';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IHomePageFields {
  /** SEO Title */
  seoTitle?: string | undefined;

  /** SEO Meta Description */
  seoMetaDescription?: string | undefined;

  /** Main Banner Text */
  mainBannerText?: string | undefined;

  /** Sub Banner Text */
  subBannerText?: string | undefined;

  /** Banner */
  banner?: Asset | undefined;

  /** Featured Image */
  featuredImage?: Asset | undefined;

  /** Featured Message Header */
  featuredMessageHeader?: string | undefined;

  /** Featured Message Body */
  featuredMessageBody?: string | undefined;

  /** Widget One Title */
  widgetOneTitle?: string | undefined;

  /** Widget One Message */
  widgetOneMessage?: string | undefined;

  /** Widget One Image */
  widgetOneImage?: Asset | undefined;

  /** Widget Two Title */
  widgetTwoTitle?: string | undefined;

  /** Widget Two Message */
  widgetTwoMessage?: string | undefined;

  /** Widget Two Image */
  widgetTwoImage?: Asset | undefined;

  /** Widget Three Title */
  widgetThreeTitle?: string | undefined;

  /** Widget Three Message */
  widgetThreeMessage?: string | undefined;

  /** Widget Three Image */
  widgetThreeImage?: Asset | undefined;

  /** Widget Four Title */
  widgetFourTitle?: string | undefined;

  /** Widget Four Message */
  widgetFourMessage?: string | undefined;

  /** Widget Four Image */
  widgetFourImage?: Asset | undefined;
}

export interface IHomePage extends Entry<IHomePageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'homePage';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IPageFields {
  /** Banner */
  banner?: Asset | undefined;

  /** Page Content */
  pageContent?: Document | undefined;

  /** Page Title */
  pageTitle?: string | undefined;

  /** SEO Title */
  seoTitle?: string | undefined;

  /** SEO Meta Description */
  seoMetaDescription?: string | undefined;
}

export interface IPage extends Entry<IPageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'page';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IReviewFields {
  /** Name */
  name?: string | undefined;

  /** Quote */
  quote?: Document | undefined;

  /** Featured Review */
  featuredReview?: boolean | undefined;
}

export interface IReview extends Entry<IReviewFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'review';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IServicePageFields {
  /** Service Title */
  serviceTitle?: string | undefined;

  /** slugText */
  slugText?: string | undefined;

  /** SEO Title */
  seoTitle?: string | undefined;

  /** SEO Meta Description */
  seoMetaDescription?: string | undefined;

  /** Service Content */
  serviceContent?: Document | undefined;

  /** Coach */
  coach?: Entry<{ [fieldId: string]: unknown }> | undefined;
}

export interface IServicePage extends Entry<IServicePageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'servicePage';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ISimplePageFields {
  /** Page Title */
  pageTitle?: string | undefined;

  /** SEO Title */
  seoTitle?: string | undefined;

  /** SEO Meta Description */
  seoMetaDescription?: string | undefined;

  /** Banner */
  banner?: Asset | undefined;
}

export interface ISimplePage extends Entry<ISimplePageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'simplePage';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export type CONTENT_TYPE =
  | 'blogPost'
  | 'coach'
  | 'homePage'
  | 'page'
  | 'review'
  | 'servicePage'
  | 'simplePage';

export type LOCALE_CODE = 'en-US';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US';
